apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lrmetrics
  namespace: lrmetrics
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: lrmetrics.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lrmetrics
                port:
                  number: 5000
