apiVersion: v1
kind: Service
metadata:
  name: lrmetrics
  namespace: lrmetrics
spec:
  selector:
    app: lrmetrics
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
